// GENERATED by scripts/extract-design-lab.ts from reference/KNOWN_Design_Lab.html. Do not edit.
// Multilingual danger phrases from the Design Lab. Checked on the phone before any AI call.
export const CRISIS = /(suicid|kill myself|end my life|want to die|don.?t want to (live|be alive)|hurt myself|self[- ]?harm|不想活|自杀|自殺|死にたい|消えたい|သေချင်|ကိုယ့်ကိုယ်ကို သတ်|انتحار|انتحر|[أا]قتل نفسي|[أا]نهي حياتي|[أا]ريد [أا]ن [أا]موت|[أا]ؤذي نفسي|لا [أا]ريد [أا]ن [أا]عيش)/i;
