// GENERATED by scripts/extract-design-lab.ts from reference/KNOWN_Design_Lab.html. Do not edit.
// Literal require() calls so Metro can bundle every image.
export const PICTURES = {
  S: require('../../assets/images/pictures/S.jpg'),
  F: require('../../assets/images/pictures/F.jpg'),
  A: require('../../assets/images/pictures/A.jpg'),
  J: require('../../assets/images/pictures/J.jpg'),
} as const;

export const SCENES = {
  ps77: require('../../assets/images/scenes/ps77.jpg'),
  welcome: require('../../assets/images/scenes/welcome.jpg'),
  done: require('../../assets/images/scenes/done.jpg'),
  neh: require('../../assets/images/scenes/neh.jpg'),
  ruth: require('../../assets/images/scenes/ruth.jpg'),
  ps142: require('../../assets/images/scenes/ps142.jpg'),
  hab: require('../../assets/images/scenes/hab.jpg'),
  hannah: require('../../assets/images/scenes/hannah.jpg'),
  hagar: require('../../assets/images/scenes/hagar.jpg'),
  mary: require('../../assets/images/scenes/mary.jpg'),
  elijah: require('../../assets/images/scenes/elijah.jpg'),
  samaritan: require('../../assets/images/scenes/samaritan.jpg'),
  joseph: require('../../assets/images/scenes/joseph.jpg'),
  close: require('../../assets/images/scenes/close.jpg'),
} as const;

export type SceneKey = keyof typeof SCENES;
