// GENERATED by scripts/extract-design-lab.ts from reference/KNOWN_Design_Lab.html. Do not edit.
// Lifted verbatim from the Design Lab's AI.local(). Order matters: first match wins.
export const STORY_RULES: [string, RegExp][] = [
      ['neh',   /(عائلتي|[أا]هلي|الوطن|بلدي|الحرب|[أا]خبار|family|friends back home|home|news|war|conflict|fighting|my country|parents|mother|father|mum|mom|dad|can.?t reach|no news|back home|家|家人|ニュース|家族|မိသားစု|သတင်း|အိမ်)/],
      ['ps142', /(وحيد|وحدي|لا [أا]حد|alone|lonely|no one|nobody|invisible|isolat|孤单|孤獨|孤独|ひとり|一人|တစ်ယောက်တည်း|အထီးကျန်)/],
      ['hab',   /(ظلم|غاضب|غضب|unfair|injustice|angry|anger|furious|why does god|wrong|不公平|生气|怒|腹が立|ဒေါသ|မတရား)/],
      ['mary',  /(مات|ماتت|وفاة|فقدت|died|death|grief|griev|lost (my|our)|funeral|去世|死了|亡くな|ဆုံးသွား|ဆုံးရှုံး)/],
      ['elijah',/(متعب|تعبت|منهك|tired|exhausted|worn out|burn(ed|t) out|give up|累|疲れ|ပင်ပန်း)/],
      ['ruth',  /(المستقبل|مستقبلي|دراستي|وظيفة|عمل|تأشيرة|فيزا|new country|new place|start(ing)? over|unknown|future|visa|career|job|internship|graduat|after (i|my) (study|studies|degree)|\bopt\b|work permit|事业|工作|前途|就職|仕事|進路|အလုပ်|新的地方|将来|未来|新しい|အနာဂတ်)/],
      ['samaritan', /(شكرا|ممتن|thank|grateful|good news|so happy|感谢|感恩|ありがとう|感謝|ကျေးဇူး)/],
      ['hagar', /([أا]ساء|ظلمني|mistreat|abuse|ran away|hurt by|no one sees|seen|欺负|いじめ|ဆက်ဆံ)/],
      ['joseph',/(خيانة|خانني|سامح|betray|forgive|forgiv|背叛|原谅|裏切|許|သစ္စာဖောက်)/],
      ['hannah',/(سعيد|فرح|happy|joy|excited|rejoic|开心|快乐|嬉しい|ပျော်)/],
      ['ps77',  /(لا [أا]ستطيع النوم|لا كلمات|لا [أا]ستطيع [أا]ن [أا]صلي|can.?t sleep|no words|can.?t pray|troubled|睡不着|眠れ|အိပ်မပျော်)/]
    ];

// Mood keywords → picture keys (internal only; never shown).
export const MOOD_RULES: [string, string, RegExp][] = [
      ['S', 'sadness',   /(\b(sad|down|cry|crying|tears|depress\w*|heartbr\w*|miss(ing)?|empty)\b|难过|伤心|悲|哭|悲しい|寂しい|泣|حزين|حزن|[أا]بكي)/],
      ['F', 'fear',      /(\b(scared|afraid|fear\w*|anxious|anxiety|worr\w*|nervous|stress\w*|overwhelm\w*|panic\w*)\b|害怕|担心|焦虑|压力|怖い|不安|心配|ストレス|خائف|خوف|قلق|توتر|ضغط)/],
      ['A', 'anger',     /(\b(mad|frustrat\w*|annoyed|irritat\w*|rage|hate|hating)\b|烦|気に入らない|イライラ|むかつ|غاضب|زعلان|منزعج)/],
      ['J', 'enjoyment', /(\b(glad|joy\w*|good day|blessed|peace\w*)\b|高兴|喜|楽しい|うれしい|فرحان|مبسوط|سلام)/]
    ];
