/**
 * Regenerates docs/CONTENT_REVIEW.md: the review list for Deb, Kezia, Dorcas
 * and the native readers. Run: npm run content:review
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { DRAFTED } from '../src/i18n/drafted';
import { LANGS } from '../src/i18n/langs';

const ROOT = join(__dirname, '..');
const applied = JSON.parse(readFileSync(join(ROOT, 'src/content/overrides.applied.json'), 'utf8')) as {
  target: string;
  value: unknown;
  previous: unknown;
  reason: string;
  status: string;
  reviewer: string;
}[];

const cell = (s: unknown) =>
  String(s ?? '')
    .replace(/\|/g, '\\|')
    .replace(/\n/g, ' ');
const fmt = (v: unknown) =>
  v && typeof v === 'object' && !Array.isArray(v)
    ? Object.entries(v as Record<string, unknown>)
        .map(([k, x]) => `**${k}**: ${typeof x === 'object' ? JSON.stringify(x) : x}`)
        .join('<br>')
    : JSON.stringify(v);

const lines: string[] = [];
lines.push(`# Content review

Generated by \`npm run content:review\` from \`scripts/content-overrides.json\` and \`src/i18n/drafted.ts\`. Nothing here has been changed in reviewed content: each item waits for the named reviewer. To approve an override, set its \`status\` to \`approved\` and its \`reviewer\`, then run \`npm run content:extract\`.

## Known content gaps (brief 2.2)

| Gap | Reviewer |
|---|---|
| **Arabic Scripture** exists only for Nehemiah 1 and Habakkuk 1; the other 14 passages show English with the note \`lang_fallback\`. Arabic UI and story copy were drafted by AI and need a native reader. | Arabic native reader |
| **Lament psalms** (13, 56, 61, 62, 139) have en, zh and ja text only (no Burmese or Arabic). Their zh/ja lines were typed from memory: check every line against 和合本 and 口語訳. | Deb |
| **Breath-prayer lines** ("Sit a little longer") are drafted. | Deb |
| **Burmese**: Judson text, UI copy and book names (၁ ဓမ္မရာဇဝင် / ၃ ဓမ္မရာဇဝင်) need a native reader. | Burmese native reader |
| **Habakkuk 1:2 in the CUV** begins with 他说：. Confirm against print. | Deb |
| **Safeguarding:** Hagar's text starts at Gen 16:11 (omits 16:9, "return to Sarai"); Elijah's starts at 1 Kgs 19:9 (omits 19:4, where he asks to die). | Kezia |
| **Hagar's full passage** includes Gen 16:12, a harsh line about her son. The critique suggests ending at 16:11 and adding 16:13. Ranges are not changed here. | Deb, Kezia |
| **Illustrations** are AI-generated and must be credited (\`docs/ASSETS.md\`). Psalm 77 and the lament psalms use the \`close\` scene. | Team |
| **Library additions** suggested by the critique (Psalm 55 for news from home; Martha and Jonah for anger) are out of scope until Deb supplies reviewed text in all 5 languages. | Deb |

## Boundary questions found by the validator

These reviewed bridge lines name her emotion, which boundary 1 forbids. They are unchanged and allow-listed so the build runs; please decide.

| Where | Text |
|---|---|
| \`bridges.en.SF.h\` | You may be worn out, and afraid of what comes next. |
| \`bridges.en.FJ.h\` | Something good happened, and part of you is afraid it won’t last. |
| \`bridges.ar.SF.h\` | ربما أنت منهك، وخائف مما سيأتي. |

Time-neutral candidates for native readers (the English check passes): \`paths.my.ps77.story\`, \`paths.ar.ps77.story\` (they may mention night as part of Asaph's story, which is fine if so).

## Drafted overrides

| Target | Status | Reviewer | Reason | Was | Now |
|---|---|---|---|---|---|
`);
for (const o of applied)
  lines.push(
    `| \`${o.target}\` | ${o.status} | ${cell(o.reviewer)} | ${cell(o.reason)} | ${cell(fmt(o.previous))} | ${cell(fmt(o.value))} |`,
  );

lines.push(`
## Drafted strings (\`src/i18n/drafted.ts\`)

New copy this build needs. Written in KNOWN's voice, not yet reviewed. Plural keys end in \`_one\`, \`_two\`, \`_few\`, \`_many\` or \`_other\`.

| Key | ${LANGS.join(' | ')} |
|---|${LANGS.map(() => '---').join('|')}|`);
const keys = [...new Set(LANGS.flatMap((l) => Object.keys(DRAFTED[l])))];
for (const k of keys) lines.push(`| \`${k}\` | ${LANGS.map((l) => cell(DRAFTED[l][k] ?? '—')).join(' | ')} |`);

writeFileSync(join(ROOT, 'docs', 'CONTENT_REVIEW.md'), lines.join('\n') + '\n', 'utf8');
console.log(`docs/CONTENT_REVIEW.md: ${applied.length} overrides, ${keys.length} drafted keys.`);
