/**
 * Extracts every reviewed content structure from the Design Lab prototype
 * (reference/KNOWN_Design_Lab.html) into src/content/ and assets/images/.
 *
 * Run with: npm run content:extract
 *
 * The prototype's copy, Scripture, matrix and flow are the spec. Nothing here
 * rewrites content: team-requested fixes are applied from
 * scripts/content-overrides.json after extraction (brief section 2.4).
 */
import { mkdirSync, readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { JSDOM, VirtualConsole } from 'jsdom';

const ROOT = join(__dirname, '..');
const SRC = join(ROOT, 'reference', 'KNOWN_Design_Lab.html');
const OUT = join(ROOT, 'src', 'content');
const IMG_OUT = join(ROOT, 'assets', 'images');
const OVERRIDES = join(ROOT, 'scripts', 'content-overrides.json');
const GENERATED = '// GENERATED by scripts/extract-design-lab.ts from reference/KNOWN_Design_Lab.html. Do not edit.';

export const LANG_CODES = ['en', 'my', 'zh', 'ja', 'ar'] as const;
type Lang = (typeof LANG_CODES)[number];

/* ---------- load the prototype in jsdom, exposing its data instead of booting it ---------- */
let html = readFileSync(SRC, 'utf8');
const hook =
  'window.__KNOWN__={D,T,BR,ORDER,EMO,MATRIX,NW,BREATH,ALT,YV,LAMENTS,IMG,SCENE,LANGS,FONTS,CRISIS:String(CRISIS),' +
  'STEPNAME,DOT,DEMO_WORDS,DEMO_REASON,AI_LOCAL:String(AI.local),AI_MATCH:String(AI.match),AI_TRANSLATE:String(AI.translate)};})();';
const before = html;
html = html.replace(/boot\(\);\s*AI\.get\(\);\s*\}\)\(\);/, hook);
if (html === before) fail('Could not find the boot() hook in the Design Lab. Has the file changed?');

const virtualConsole = new VirtualConsole();
virtualConsole.on('jsdomError', (e) => {
  if (!/Not implemented/.test(String(e.message))) console.warn('[jsdom]', e.message);
});
const dom = new JSDOM(html, {
  runScripts: 'dangerously',
  url: 'https://known.local/',
  pretendToBeVisual: true,
  virtualConsole,
});
const K = (dom.window as any).__KNOWN__;
if (!K) fail('The Design Lab script did not expose __KNOWN__.');

// Deep-copy out of the jsdom realm so JSON and prototypes are plain.
const plain = <T>(x: T): T => JSON.parse(JSON.stringify(x));
const D = plain(K.D);
const T = plain(K.T);
const BR = plain(K.BR);
const BREATH = plain(K.BREATH);

/* ---------- asserts (brief section 4.1): fail loudly ---------- */
const problems: string[] = [];
const expect = (label: string, actual: unknown, wanted: unknown) => {
  if (JSON.stringify(actual) !== JSON.stringify(wanted))
    problems.push(`${label}: expected ${JSON.stringify(wanted)}, got ${JSON.stringify(actual)}`);
};
const count = (o: object | undefined) => (o ? Object.keys(o).length : 0);

expect('passages', count(D.PASSAGES), 16);
for (const l of LANG_CODES) expect(`paths.${l}`, count(D.PATHS[l]), 16);
expect('T.en keys', count(T.en), 111);
for (const l of LANG_CODES) expect(`PW_UI.${l} keys`, count(D.PW_UI[l]), 174);
for (const l of LANG_CODES) expect(`BR.${l} keys`, count(BR[l]), 11);
expect('BREATH keys', count(BREATH), 16);
expect('pictures', Object.keys(K.IMG).sort(), ['A', 'F', 'J', 'S']);
expect('scenes', count(K.SCENE), 14);
const arPassages = Object.keys(D.PASSAGES)
  .filter((k) => D.PASSAGES[k].text.ar && count(D.PASSAGES[k].text.ar) > 0)
  .sort();
expect('Arabic passage text', arPassages, ['hab', 'neh']);
expect('ORDER', K.ORDER, ['S', 'F', 'A', 'J']);
expect('NW', K.NW, 'ps77');
expect('LAMENTS', K.LAMENTS, ['ps61', 'ps13', 'ps62', 'ps56', 'ps139']);
expect(
  'LANGS',
  K.LANGS.map((l: { code: string }) => l.code),
  ['en', 'my', 'zh', 'ja', 'ar'],
);
if (problems.length) fail('Content counts differ from the brief:\n  - ' + problems.join('\n  - '));

/* ---------- build the content pack ---------- */
const strings: Record<Lang, Record<string, string>> = {} as never;
for (const l of LANG_CODES) strings[l] = { ...D.PW_UI[l], ...T[l] };

const pack = {
  passages: D.PASSAGES as Record<string, unknown>,
  books: D.BOOKS as Record<string, unknown>,
  versions: D.VERSIONS as Record<string, unknown>,
  paths: D.PATHS as Record<Lang, Record<string, Record<string, unknown>>>,
  strings,
  bridges: BR as Record<Lang, Record<string, { h: string; p: string }>>,
  breath: BREATH as Record<string, unknown>,
  matrix: { order: K.ORDER, matrix: plain(K.MATRIX), nw: K.NW },
  alt: plain(K.ALT),
  laments: plain(K.LAMENTS),
  langs: plain(K.LANGS),
  steps: { dot: plain(K.DOT), stepName: plain(K.STEPNAME) },
  storyChapters: {} as Record<string, unknown>,
};

/* ---------- apply reviewed overrides (section 2.4) ---------- */
type Override = {
  target: string;
  value: unknown;
  reason: string;
  status: 'drafted' | 'approved';
  reviewer: string;
};
const overrides: Override[] = existsSync(OVERRIDES) ? JSON.parse(readFileSync(OVERRIDES, 'utf8')).overrides : [];
const PER_LANG = new Set(['paths', 'strings', 'bridges']);
const applied: (Override & { previous: unknown })[] = [];

for (const o of overrides) {
  if (!['drafted', 'approved'].includes(o.status)) fail(`Override ${o.target}: status must be drafted or approved`);
  if (!o.reason) fail(`Override ${o.target}: a reason is required`);
  const segs = parseTarget(o.target);
  const file = segs.shift() as string;
  if (!(file in pack)) fail(`Override ${o.target}: unknown content file "${file}"`);
  if (PER_LANG.has(file)) {
    const langSeg = segs.shift() as string;
    const langs = langSeg === '*' ? LANG_CODES : [langSeg as Lang];
    const values = o.value as Record<string, unknown>;
    const previous: Record<string, unknown> = {};
    for (const l of langs) {
      if (!(l in values)) fail(`Override ${o.target}: missing value for "${l}"`);
      previous[l] = setAt((pack as never)[file][l], segs, values[l], o.target);
    }
    applied.push({ ...o, previous });
  } else {
    applied.push({ ...o, previous: setAt((pack as never)[file], segs, o.value, o.target) });
  }
}

/* ---------- write files ---------- */
// Keep rotation.json: it is team-editable data written by build-rotation.ts.
const keep = join(OUT, 'rotation.json');
const keptRotation = existsSync(keep) ? readFileSync(keep) : null;
rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
if (keptRotation) writeFileSync(keep, keptRotation);
const write = (name: string, data: unknown) =>
  writeFileSync(join(OUT, name), JSON.stringify(data, null, 2) + '\n', 'utf8');

write('passages.json', pack.passages);
write('books.json', pack.books);
write('versions.json', pack.versions);
for (const l of LANG_CODES) {
  write(`paths.${l}.json`, pack.paths[l]);
  write(`strings.${l}.json`, pack.strings[l]);
  write(`bridges.${l}.json`, pack.bridges[l]);
}
write('breath.json', pack.breath);
write('matrix.json', pack.matrix);
write('alt.json', pack.alt);
write('laments.json', pack.laments);
write('langs.json', pack.langs);
write('steps.json', pack.steps);
write('story-chapters.json', pack.storyChapters);
write('overrides.applied.json', applied);
// Judge panel only. Emotion names are never shown to the student (boundary 1).
write('panel.json', {
  emo: plain(K.EMO),
  demoWords: K.DEMO_WORDS,
  demoReason: K.DEMO_REASON,
  yvPrototypeGuesses: plain(K.YV),
});

// The prototype's on-device matcher rules, lifted verbatim from AI.local().
const localSrc: string = K.AI_LOCAL;
const rulesSrc = sliceBetween(localSrc, 'const rules = ', ';\n    for');
const moodsSrc = sliceBetween(localSrc, 'const moods = ', ';\n    const hit');
writeFileSync(
  join(OUT, 'matcher-rules.ts'),
  `${GENERATED}
// Lifted verbatim from the Design Lab's AI.local(). Order matters: first match wins.
export const STORY_RULES: [string, RegExp][] = ${rulesSrc};

// Mood keywords → picture keys (internal only; never shown).
export const MOOD_RULES: [string, string, RegExp][] = ${moodsSrc};
`,
  'utf8',
);

writeFileSync(
  join(OUT, 'crisis.ts'),
  `${GENERATED}
// Multilingual danger phrases from the Design Lab. Checked on the phone before any AI call.
export const CRISIS = ${K.CRISIS};
`,
  'utf8',
);

// Prompts are kept for the relay (relay/src/prompts.ts ports them); stored here for diffing.
write('prototype-prompts.json', { match: K.AI_MATCH, translate: K.AI_TRANSLATE });

/* ---------- images ---------- */
const decode = (uri: string) => {
  const m = /^data:image\/(jpeg|jpg|png);base64,(.+)$/.exec(uri);
  if (!m) fail('Unexpected image data URI');
  if (m![1] === 'png') fail('Expected JPEG images');
  return Buffer.from(m![2], 'base64');
};
const picDir = join(IMG_OUT, 'pictures');
const sceneDir = join(IMG_OUT, 'scenes');
rmSync(picDir, { recursive: true, force: true });
rmSync(sceneDir, { recursive: true, force: true });
mkdirSync(picDir, { recursive: true });
mkdirSync(sceneDir, { recursive: true });
for (const k of K.ORDER as string[]) writeFileSync(join(picDir, `${k}.jpg`), decode(K.IMG[k]));
const sceneKeys = Object.keys(K.SCENE);
for (const k of sceneKeys) writeFileSync(join(sceneDir, `${k}.jpg`), decode(K.SCENE[k]));

writeFileSync(
  join(OUT, 'images.ts'),
  `${GENERATED}
// Literal require() calls so Metro can bundle every image.
export const PICTURES = {
${(K.ORDER as string[]).map((k) => `  ${k}: require('../../assets/images/pictures/${k}.jpg'),`).join('\n')}
} as const;

export const SCENES = {
${sceneKeys.map((k) => `  ${k}: require('../../assets/images/scenes/${k}.jpg'),`).join('\n')}
} as const;

export type SceneKey = keyof typeof SCENES;
`,
  'utf8',
);

writeFileSync(
  join(OUT, 'README.md'),
  `# src/content (generated)\n\nWritten by \`scripts/extract-design-lab.ts\` from \`reference/KNOWN_Design_Lab.html\`.\nDo not hand-edit. Team-requested fixes go in \`scripts/content-overrides.json\`.\n`,
);

console.log(
  `Extracted ${count(pack.passages)} passages, 16 paths × ${LANG_CODES.length} languages, ` +
    `${count(pack.strings.en)} English strings, ${sceneKeys.length} scenes, 4 pictures; ` +
    `${applied.length} overrides applied (${applied.filter((o) => o.status === 'drafted').length} drafted).`,
);

/* ---------- helpers ---------- */
function fail(msg: string): never {
  console.error(`\n✖ extract-design-lab: ${msg}\n`);
  process.exit(1);
}
function sliceBetween(s: string, start: string, end: string) {
  const a = s.indexOf(start);
  const b = s.indexOf(end, a);
  if (a < 0 || b < 0) fail(`Could not find "${start}" in AI.local()`);
  return s.slice(a + start.length, b).trim();
}
/** "paths.*.hannah.options[3]" → ['paths','*','hannah','options',3] */
function parseTarget(t: string): (string | number)[] {
  const out: (string | number)[] = [];
  for (const part of t.split('.')) {
    const m = /^([^[\]]+)((?:\[\d+\])*)$/.exec(part);
    if (!m) fail(`Bad override target "${t}"`);
    out.push(m![1]);
    for (const idx of m![2].matchAll(/\[(\d+)\]/g)) out.push(Number(idx[1]));
  }
  return out;
}
function setAt(obj: Record<string | number, unknown>, segs: (string | number)[], value: unknown, label: string) {
  let o = obj;
  for (let i = 0; i < segs.length - 1; i++) {
    if (o[segs[i]] == null) {
      if (typeof segs[i + 1] === 'number') fail(`Override ${label}: path does not exist`);
      o[segs[i]] = {};
    }
    o = o[segs[i]] as Record<string | number, unknown>;
  }
  const last = segs[segs.length - 1];
  const previous = o[last] ?? null;
  o[last] = value;
  return previous;
}
